// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:ef3cf024-d0a4-4123-8e5b-92071e502101",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_lZzOPHXc5",
    "aws_user_pools_web_client_id": "2jikemme4vrb7pnrap9olpqbd2",
    "oauth": {
        "domain": "reactlogine50fbcb2-e50fbcb2-jeno.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/login/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
